# Generated by Django 4.2.6 on 2023-11-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_people_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
