# Generated by Django 4.2.6 on 2023-11-20 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_machines_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='userId',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.users'),
        ),
    ]
